language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - make venv
script:
  - make all
  - make clean
after_success:
  - test $TRAVIS_BRANCH = "master" -o $TRAVIS_BRANCH = "dev" && bash <(curl -s https://codecov.io/bash)
